name: remote-mcp-server
region: fra
services:
  - name: remote-mcp-server
    github:
      repo: estkae/remote-mcp-server
      branch: main
      deploy_on_push: true

    # Build Configuration
    build_command: npm install

    # Run Configuration
    run_command: node start-with-downloads.js

    # Environment Settings
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1

    # HTTP Port
    http_port: 8080

    # Environment Variables
    envs:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: "8080"

      - key: SERVER_URL
        value: https://remote-mcp-server-8h8cr.ondigitalocean.app

      - key: OUTPUT_DIR
        value: /tmp/output

      # Füge hier weitere ENV-Variablen hinzu (AZURE, etc.)
      # - key: AZURE_CLIENT_ID
      #   value: YOUR_VALUE
      #   scope: RUN_TIME
      #   type: SECRET

    # Health Check
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Routes
    routes:
      - path: /
